name: SAWP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7

      # Process all Starred Repositoties from an User
      - name: Create star list
        id: sawp-job
        uses: ./
        with:
          github-user: ${{ github.actor }} # Or any GitHub Username
          github-token: ${{ secrets.GITHUB_TOKEN }}
          db-connection-url: ${{ secrets.DB_CONN_URL }} # Supabase connection string "postgresql://postgres..."
